name: Feature Suggestion
description: Suggest a feature for the 5e Reshaped project
title: "[Feature]: "
labels: ["Feature Discussion"]
type: Feature
assignees:
  - kurohyou
body:
  - type: markdown
    attributes:
      label: What is the feature you are requesting?
      description: Suggested Features should be specific functionality that is broadly applicable.
      render: markdown
  - type: markdown
    attributes:
      label: Benefit
      description: What benefit does this provide?
      render: markdown
  - type: markdown
    attributes:
      label: Issues/Problems
      description: Do you forsee any issues with this feature?
      render: markdown
